/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import main.FunctionsTXT;

/**
 *
 * @author isaac
 */
public class SearchArticlePage extends javax.swing.JFrame {

    /**
     * Creates new form searchArticlePage
     */
    public SearchArticlePage() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                int selectedOption = JOptionPane.showOptionDialog(null, "Guardar los datos en la base de datos",
                         "¿Desea guardar los datos?" ,
                         JOptionPane.YES_NO_OPTION,
                         JOptionPane.QUESTION_MESSAGE,
                         null,
                         new Object[] { "Sí", "No"},
                         "No");
                if (selectedOption == JOptionPane.YES_OPTION) {
                    FunctionsTXT.save();
                }
                e.getWindow().dispose();
                System.exit(0);
            }
        });
    }
    
    /**
     * Return the combo box
     * @return Author Combo Box
     */
    public JComboBox<String> getAuthorComboBox() {
        return AuthorComboBox;
    }
    
    
    /**
     * Return the combo box
     * @return KeyWords Combo Box
     */
    public JComboBox<String> getAuthorArticleTitleComboBox() {
        return AuthorArticleTitleComboBox;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        title10 = new javax.swing.JLabel();
        title7 = new javax.swing.JLabel();
        AuthorSearchButton2 = new javax.swing.JToggleButton();
        KeyWordSearchButton = new javax.swing.JToggleButton();
        KeyWordArticleTitleComboBox = new javax.swing.JComboBox<>();
        KeyWordsTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        backToMenuButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        title4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        title3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        title9 = new javax.swing.JLabel();
        title6 = new javax.swing.JLabel();
        AuthorComboBox = new javax.swing.JComboBox<>();
        AuthorSearchTitleButton = new javax.swing.JToggleButton();
        AuthorSearchButton = new javax.swing.JToggleButton();
        AuthorArticleTitleComboBox = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        title5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        titleSearchTextField = new javax.swing.JTextArea();
        titleSearchButton = new javax.swing.JButton();
        title8 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 204, 204));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        title10.setText("Seleccione el articulo");
        jPanel7.add(title10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        title7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        title7.setText("Seleccione palabra clave");
        jPanel7.add(title7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        AuthorSearchButton2.setText("Ver info");
        AuthorSearchButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthorSearchButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(AuthorSearchButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 90, -1));

        KeyWordSearchButton.setText("Buscar");
        KeyWordSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeyWordSearchButtonActionPerformed(evt);
            }
        });
        jPanel7.add(KeyWordSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 90, -1));

        KeyWordArticleTitleComboBox.setBackground(new java.awt.Color(255, 153, 153));
        jPanel7.add(KeyWordArticleTitleComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 400, -1));

        KeyWordsTextField.setBackground(new java.awt.Color(255, 153, 153));
        jPanel7.add(KeyWordsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 400, 30));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 680, 90));

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/logo.png"))); // NOI18N
        jPanel2.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        title1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        title1.setText("Buscar Artículo");
        jPanel2.add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 70));

        backToMenuButton.setText("Volver al menú");
        backToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backToMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        title4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title4.setText("Título");
        jPanel1.add(title4, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 10, 670, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 680, 40));

        jPanel4.setBackground(new java.awt.Color(255, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        title3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title3.setText("Autor");
        jPanel4.add(title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 10, 670, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 680, 40));

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        title.setText(" Palabra Clave");
        jPanel3.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 680, 40));

        jPanel6.setBackground(new java.awt.Color(255, 204, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        title9.setText("Selecciona el articulo");
        jPanel6.add(title9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        title6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        title6.setText("Seleccione el autor");
        jPanel6.add(title6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        AuthorComboBox.setBackground(new java.awt.Color(255, 153, 153));
        AuthorComboBox.setMinimumSize(new java.awt.Dimension(100, 100));
        AuthorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthorComboBoxActionPerformed(evt);
            }
        });
        jPanel6.add(AuthorComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 400, -1));

        AuthorSearchTitleButton.setText("Ver info");
        AuthorSearchTitleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthorSearchTitleButtonActionPerformed(evt);
            }
        });
        jPanel6.add(AuthorSearchTitleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 90, -1));

        AuthorSearchButton.setText("Buscar");
        AuthorSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthorSearchButtonActionPerformed(evt);
            }
        });
        jPanel6.add(AuthorSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 90, -1));

        AuthorArticleTitleComboBox.setBackground(new java.awt.Color(255, 153, 153));
        jPanel6.add(AuthorArticleTitleComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 400, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 680, 90));

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        title5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        title5.setText("articulo a buscar");
        jPanel5.add(title5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 210, -1));

        titleSearchTextField.setBackground(new java.awt.Color(255, 153, 153));
        titleSearchTextField.setColumns(20);
        titleSearchTextField.setLineWrap(true);
        titleSearchTextField.setRows(5);
        jScrollPane1.setViewportView(titleSearchTextField);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 400, 60));

        titleSearchButton.setText("Buscar");
        titleSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleSearchButtonActionPerformed(evt);
            }
        });
        jPanel5.add(titleSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 90, -1));

        title8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        title8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        title8.setText("Introduzca el título del ");
        jPanel5.add(title8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 210, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 680, 90));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/output-onlinepngtools.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-660, 0, 1390, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenuButtonActionPerformed
        GlobalUI.openMainPage();
    }//GEN-LAST:event_backToMenuButtonActionPerformed

    private void titleSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleSearchButtonActionPerformed
        FunctionsUI.findArticleByName(titleSearchTextField.getText());
    }//GEN-LAST:event_titleSearchButtonActionPerformed

    private void AuthorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthorComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AuthorComboBoxActionPerformed

    private void AuthorSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthorSearchButtonActionPerformed
    FunctionsUI.fillAuthorArticleTitleComboBox( AuthorArticleTitleComboBox, AuthorComboBox);
    }//GEN-LAST:event_AuthorSearchButtonActionPerformed

    private void AuthorSearchTitleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthorSearchTitleButtonActionPerformed
        FunctionsUI.getArticleTitle(AuthorArticleTitleComboBox);
    }//GEN-LAST:event_AuthorSearchTitleButtonActionPerformed

    private void KeyWordSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeyWordSearchButtonActionPerformed
        FunctionsUI.fillKeyWordArticleTitleComboBox( KeyWordArticleTitleComboBox, KeyWordsTextField);
    }//GEN-LAST:event_KeyWordSearchButtonActionPerformed

    private void AuthorSearchButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthorSearchButton2ActionPerformed
        FunctionsUI.getArticleTitle(KeyWordArticleTitleComboBox);
    }//GEN-LAST:event_AuthorSearchButton2ActionPerformed
    /**
     * Getter for titleSearchTextField
     * @return JTextArea
     */
    public JTextArea getTitleSearchTextField() {
        return titleSearchTextField;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchArticlePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchArticlePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchArticlePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchArticlePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchArticlePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AuthorArticleTitleComboBox;
    private javax.swing.JComboBox<String> AuthorComboBox;
    private javax.swing.JToggleButton AuthorSearchButton;
    private javax.swing.JToggleButton AuthorSearchButton2;
    private javax.swing.JToggleButton AuthorSearchTitleButton;
    private javax.swing.JComboBox<String> KeyWordArticleTitleComboBox;
    private javax.swing.JToggleButton KeyWordSearchButton;
    private javax.swing.JTextField KeyWordsTextField;
    private javax.swing.JButton backToMenuButton;
    private javax.swing.JLabel background;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title10;
    private javax.swing.JLabel title3;
    private javax.swing.JLabel title4;
    private javax.swing.JLabel title5;
    private javax.swing.JLabel title6;
    private javax.swing.JLabel title7;
    private javax.swing.JLabel title8;
    private javax.swing.JLabel title9;
    private javax.swing.JButton titleSearchButton;
    private javax.swing.JTextArea titleSearchTextField;
    // End of variables declaration//GEN-END:variables
}
